#%RAML 1.0
title: APIdrop
uses:
  Apidrop: NewLibrary.raml
version: v1
baseUri: http://api.samplehost.com
/Usuario:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message" : "Hello World"
              }
/Equipos:
  get:
    queryParameters:
      key:
  post:
  put:
